# Generated by Django 2.2.2 on 2020-08-27 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicios',
            fields=[
                ('IdEjercicio', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('NombreProblema', models.CharField(max_length=20)),
                ('skill1', models.BooleanField()),
                ('skill2', models.BooleanField()),
                ('skill3', models.BooleanField()),
                ('skill4', models.BooleanField()),
                ('knowledge1', models.NullBooleanField()),
                ('knowledge2', models.NullBooleanField()),
                ('knowledge3', models.NullBooleanField()),
                ('knowledge4', models.NullBooleanField()),
                ('complejidad', models.CharField(max_length=20)),
                ('hito', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('UsuarioUnab', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('rut', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('UsuarioUnab', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('Coordinador', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Ramo',
            fields=[
                ('CodigoRamo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('NombreRamo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('nrc', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('semestre', models.CharField(max_length=20)),
                ('CodigoRamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargadatos.Ramo')),
                ('UsuarioUnab', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cargadatos.Profesor')),
            ],
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('nrc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cargadatos.Seccion')),
                ('UsuarioUnab', models.EmailField(max_length=254)),
                ('notas', models.DecimalField(decimal_places=3, max_digits=20)),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TablonEjercicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=20)),
                ('mes', models.CharField(max_length=20)),
                ('año', models.CharField(max_length=20)),
                ('Puntaje', models.DecimalField(decimal_places=3, max_digits=20)),
                ('IdEjercicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cargadatos.Ejercicios')),
                ('UsuarioUnab', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cargadatos.Estudiante')),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='nrc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cargadatos.Lista'),
        ),
    ]
